resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 1000
        ignoreException:
          - java.util.NoSuchElementException
    instances:
      retryService:
        baseConfig: default
        maxRetryAttempts: 3